project:
  output-dir: _output
  render:
    - consejos-cpp.qmd
    - excepciones-cpp.qmd

subtitle: Sistemas Operativos {{< var academic-year >}}

lang: es
abstract-title: Resumen
toc-title: Contenidos
toc: true
number-sections: true

format:
  pdf:
    classoption: numbers=endperiod
    papersize: a4
    latex-tlmgr-opts:
      - "--repository=https://eu.mirrors.cicku.me/ctan/systems/texlive/tlnet/"
